on:
  push:
    tag:
      - 'v*'

jobs:

  test:
    name: ${{ matrix.OS }}

    strategy:
      matrix:
        OS: [ ubuntu-22.04, ubuntu-20.04 ]
    runs-on: ${{ matrix.OS }}

    steps:

    - uses: actions/checkout@v3

    - name: Update $PATH
      run: |
        echo $PATH
        echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
    - name: Check $PATH
      run: echo $PATH

    - name: Install SBCL
      run: sudo apt install sbcl

    - name: Install quicklisp
      run: |
        wget https://beta.quicklisp.org/quicklisp.lisp
        sbcl --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --quit

    - name: Place cl-repl in quicklisp/local-projects
      run: |
        mkdir $HOME/quicklisp/local-projects/cl-repl
        cp -R /home/runner/work/cl-repl/cl-repl/* $HOME/quicklisp/local-projects/cl-repl

    - name: Dump lisp image
      run: |
        sbcl --eval '(ql:quickload "cl-repl")' --eval '(asdf:make "cl-repl")'

    - name: Rename lisp image
      run: |
        cd ~/quicklisp/local-projects/cl-repl/
        mv cl-repl ~/cl-repl.${{matrix.OS}}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: cl-repl.${{matrix.OS}}
